image: node:8-alpine

before_script:
- apk add --no-cache git
- yarn

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: deps
  paths:
  - node_modules/

test:lint:
  script:
  - yarn run lint
